version: '3.8'

services:

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: trial
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: